### PR TITLE
Add password reset test

### PR DESCRIPTION
**Pull request by wilburpowery**
I closed the last PR since my fork got fu@&&^ up. 
I really have no idea how to test the other part of the password reset functionality, where you enter your email and new password and it checks for a valid token in the database in the `password-resets` table. 

Feel free to merge this PR now, and later on I'll keep adding more tests.

### CODE REVIEW

**Comment by assertchris** [comment]
Just tried this locally, and I think you forgot to commit the changes you made to the views.

**Comment by wilburpowery** [comment]
Correct, man. Just pushed up that commit.

**Comment by assertchris** [comment]
Apart from the expected search failure (need to make that skip somehow), there's a failure on sending email (which makes sense). We need to think of a way to mock that so that it doesn't continue to fail. Going to merge this, for now, since I don't think it's your problem to sort out.

Thank you for the work! :)

**Comment by wilburpowery** [comment]
I think theres a `fake` method on the Mail facade. Not sure if it's ok to use that on browser tests. I'l look into that! 😁

**Pull request merged**
