### PR TITLE
Use models in seeders

### PR DESCRIPTION
**Pull request by assertchris**
The main reason for doing this is to make sure any model logic can continue to execute as part of the automated tests.

Edit: for instance, I [picked up a user handle issue](https://github.com/assertchris/borrow-my-topic/pull/76/commits/5a9dac333220b51ebfadf798735ba00c3c2d1747) just by using the models and their default behaviour.

### CODE REVIEW

**Comment by ludo237** [comment]
I think factories are a better solution for seeding aren't they?

**Comment by assertchris** [comment]
@ludo237 yeah, but I do want some sensible and predictable names for things. Hence using real user details (so we can reliably authenticate in tests) and real topic names (so we can test search functionality).

**Comment by ludo237** [comment]
Umh fair enough

**Comment by wilburpowery** [comment]
Agreed. Seeders are more helpful in this case.

**Pull request merged**
